import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { X } from "lucide-react";
import type { AIProviderName, Match, MatchEvent } from "../../types";
import { api } from "../../lib/api";
import { eventIcon, eventLabel } from "../../lib/utils";
import { AIResponse } from "../ai/AIResponse";
import { computeResponseConfidence } from "../../lib/predictions";

interface Props {
  match: Match;
  event: MatchEvent | null;
  onClose: () => void;
}

export function ExplainDrawer({ match, event, onClose }: Props) {
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState<string>();
  const [provider, setProvider] = useState<AIProviderName>();
  const closeRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (!event) return;
    let active = true;
    setLoading(true);
    setText(undefined);
    api.explain(match.id, event.id).then((res) => {
      if (!active) return;
      setText(res.text);
      setProvider(res.provider);
      setLoading(false);
    });
    requestAnimationFrame(() => closeRef.current?.focus());
    return () => {
      active = false;
    };
  }, [event, match.id]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <AnimatePresence>
      {event && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm"
            aria-hidden
          />
          <motion.aside
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 30, stiffness: 280 }}
            className="fixed right-0 top-0 z-50 flex h-full w-full max-w-md flex-col glass-strong border-l border-white/10 p-4 sm:p-6"
            role="dialog"
            aria-modal="true"
            aria-label={`AI explanation for ${event?.player}'s ${eventLabel(event?.type ?? "goal")}`}
          >
            <div className="mb-5 flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2 text-2xl">
                  <span aria-hidden>{eventIcon(event.type)}</span>
                  <span className="text-sm font-bold uppercase tracking-wide text-slate-400">
                    {eventLabel(event.type)} · {event.minute}'
                  </span>
                </div>
                <h2 className="mt-1 text-xl font-extrabold" id="explain-title">{event.player}</h2>
              </div>
              <button
                ref={closeRef}
                onClick={onClose}
                className="rounded-lg p-2 text-slate-400 hover:bg-white/10 transition-colors focus-visible:ring-2 focus-visible:ring-pitch-400/60"
                aria-label="Close explanation"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <p className="mb-4 rounded-xl bg-white/5 p-3 text-sm text-slate-300">{event.detail}</p>

            <AIResponse loading={loading} text={text} provider={provider} title="Why it happened" confidence={text && provider ? computeResponseConfidence(provider, match, "explain") : undefined} />

            <p className="mt-auto pt-4 text-center text-[11px] text-slate-500">
              Explanation generated by GoalVision AI · grounded in this match's data
            </p>
          </motion.aside>
        </>
      )}
    </AnimatePresence>
  );
}
